"""initial

Revision ID: 463a709ab248
Revises: 
Create Date: 2026-05-04 14:03:32.313532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '463a709ab248'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'analyzing', 'complete', 'failed', name='sessionstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frames',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Float(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_session_id'), 'frames', ['session_id'], unique=False)
    op.create_table('tracked_persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_ms', sa.Float(), nullable=False),
    sa.Column('last_seen_ms', sa.Float(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=32), nullable=True),
    sa.Column('avg_intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_persons_session_id'), 'tracked_persons', ['session_id'], unique=False)
    op.create_table('emotion_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('peak_timestamp_ms', sa.Float(), nullable=False),
    sa.Column('start_ms', sa.Float(), nullable=False),
    sa.Column('end_ms', sa.Float(), nullable=False),
    sa.Column('peak_emotion', sa.String(length=32), nullable=False),
    sa.Column('peak_intensity', sa.Float(), nullable=False),
    sa.Column('clip_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['tracked_persons.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_clips_session_id'), 'emotion_clips', ['session_id'], unique=False)
    op.create_table('emotion_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Float(), nullable=False),
    sa.Column('angry', sa.Float(), nullable=True),
    sa.Column('disgust', sa.Float(), nullable=True),
    sa.Column('fear', sa.Float(), nullable=True),
    sa.Column('happy', sa.Float(), nullable=True),
    sa.Column('sad', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('neutral', sa.Float(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=32), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_w', sa.Float(), nullable=True),
    sa.Column('bbox_h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['tracked_persons.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['therapy_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_records_frame_id'), 'emotion_records', ['frame_id'], unique=False)
    op.create_index(op.f('ix_emotion_records_person_id'), 'emotion_records', ['person_id'], unique=False)
    op.create_index(op.f('ix_emotion_records_session_id'), 'emotion_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_records_session_id'), table_name='emotion_records')
    op.drop_index(op.f('ix_emotion_records_person_id'), table_name='emotion_records')
    op.drop_index(op.f('ix_emotion_records_frame_id'), table_name='emotion_records')
    op.drop_table('emotion_records')
    op.drop_index(op.f('ix_emotion_clips_session_id'), table_name='emotion_clips')
    op.drop_table('emotion_clips')
    op.drop_index(op.f('ix_tracked_persons_session_id'), table_name='tracked_persons')
    op.drop_table('tracked_persons')
    op.drop_index(op.f('ix_frames_session_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_table('therapy_sessions')
    # ### end Alembic commands ###
